# Generated by Django 4.1.2 on 2024-06-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_empleado',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
