# Generated by Django 4.1.2 on 2024-06-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0002_empleado_id_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.CharField(editable=False, max_length=10, unique=True)),
                ('numero_interno', models.IntegerField(verbose_name='N° INT.')),
                ('tipo_equipo', models.CharField(max_length=255, verbose_name='TIPO EQUIPO')),
                ('sam', models.CharField(max_length=255, verbose_name='SAM')),
                ('nuevo_codigo', models.CharField(max_length=255, verbose_name='NUEVO COD.')),
                ('año', models.IntegerField(verbose_name='AÑO')),
                ('marca', models.CharField(max_length=255, verbose_name='MARCA')),
                ('modelo_maquina', models.CharField(max_length=255, verbose_name='MOD. MAQ.')),
                ('consumo_promedio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CONSUM. PROM')),
                ('fecha_actualizacion', models.DateField(verbose_name='FECHA DE ACTUALIZACION')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='UBICACIÓN')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=255, verbose_name='RUTA')),
                ('distrito', models.IntegerField(verbose_name='DISTRITO')),
                ('zona', models.CharField(choices=[('Chaco', 'Chaco'), ('Centro', 'Centro'), ('Cintis', 'Cintis'), ('Norte', 'Norte')], max_length=10, verbose_name='ZONA')),
                ('seccion', models.CharField(max_length=255, verbose_name='SECCION')),
                ('longitud_km', models.IntegerField(verbose_name='LONG. Km')),
                ('km_inicial', models.IntegerField(verbose_name='KM INICIAL')),
                ('km_final', models.IntegerField(verbose_name='KM FINAL')),
                ('tramo', models.CharField(max_length=255, verbose_name='TRAMO')),
                ('lugar_inicial', models.CharField(max_length=255, verbose_name='LUGAR INICIAL')),
                ('lugar_final', models.CharField(max_length=255, verbose_name='LUGAR FINAL')),
                ('pavimento', models.BooleanField(default=False, verbose_name='PAV.')),
                ('empedrado', models.BooleanField(default=False, verbose_name='EMPEDRADO')),
                ('ripio', models.BooleanField(default=False, verbose_name='RIPIO')),
                ('tierra', models.BooleanField(default=False, verbose_name='TIERRA')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
    ]
