# Generated by Django 4.1.2 on 2024-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0003_equipo_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='N°')),
                ('codigo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CODIGO')),
                ('grupo', models.IntegerField(verbose_name='GRUPO')),
                ('actividad', models.CharField(max_length=255, verbose_name='ACTIVIDAD')),
                ('subactividad', models.CharField(max_length=255, verbose_name='SUBACTIVIDAD')),
                ('unidad', models.CharField(max_length=255, verbose_name='UNIDAD')),
                ('produccion_diaria_min', models.FloatField(verbose_name='PRODUCC DIARIA [MIN]')),
                ('produccion_diaria_max', models.FloatField(verbose_name='PRODUCC DIARIA [MAX]')),
                ('produccion_diaria_prom', models.FloatField(verbose_name='PRODUCC DIARIA [PROM]')),
                ('produccion_unid_hr_prom', models.FloatField(verbose_name='PRODUCC UNID/HR [PROM]')),
                ('produccion_hr_unid_prom', models.FloatField(verbose_name='PRODUCC HR/UNID [PROM]')),
                ('camioneta', models.BooleanField(default=False, verbose_name='CAMIONETA')),
                ('motoniveladora', models.BooleanField(default=False, verbose_name='MOTONIVELADORA')),
                ('camion_aguatero', models.BooleanField(default=False, verbose_name='CAMION AGUATERO')),
                ('bomba_de_agua', models.BooleanField(default=False, verbose_name='BOMBA DE AGUA')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
