# Generated by Django 4.1.2 on 2024-06-30 20:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0004_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='id',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ruta',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='RUTA'),
        ),
        migrations.CreateModel(
            name='Proyecto_DE5',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de proyecto')),
                ('nro_interno', models.CharField(max_length=255, verbose_name='N.° interno de proyecto')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Proyecto')),
                ('provincia', models.CharField(max_length=255, verbose_name='Provincia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.empleado', verbose_name='Director o Encargado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ControlMensualEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], editable=False, verbose_name='DIA')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='FECHA')),
                ('codigo_operacion', models.CharField(max_length=255, verbose_name='COD. OPE.')),
                ('alm_5', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ALM-5')),
                ('gasolina', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GASOLINA')),
                ('diesel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='DIESEL')),
                ('horometro_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HOROMETRO INICIAL')),
                ('horometro_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HOROMETRO FINAL')),
                ('horas_operadas', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='HORAS OPERADAS')),
                ('cantidad', models.IntegerField(verbose_name='CANTIDAD')),
                ('pasadas', models.IntegerField(verbose_name='PASADAS')),
                ('lubricante_15w40_gasolina', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='15W-40 Gasolina')),
                ('lubricante_15w40_diesel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='15W-40 Diesel')),
                ('lubricante_aoh68_hidraulico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='AOH-68 Hidraulico')),
                ('lubricante_85w140', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='85W-140')),
                ('lubricante_80w90', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='80W-90')),
                ('lubricante_mt1_10w_transm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MT1-10W TRANSM')),
                ('lubricante_tipo_a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TIPO A')),
                ('anticongelante', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ANTICONGELANTE')),
                ('liquido_frenos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='LIQUID. FRENOS')),
                ('grasa_rodam_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='RODAM')),
                ('grasa_chasis_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CHASIS')),
                ('hrs_disponibilidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS DISP.')),
                ('hrs_combustible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS COMB.')),
                ('hrs_lubricantes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS LUB.')),
                ('hrs_repuestos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS REPU.')),
                ('hrs_operador', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS OPE.')),
                ('hrs_tiempo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS TIEM.')),
                ('hrs_reparacion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS REPA.')),
                ('hrs_mantenimiento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS MTO.')),
                ('hrs_otros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRS OTROS')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.actividad', verbose_name='ACTIVIDAD')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.proyecto_de5', verbose_name='Proyecto')),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.ruta', verbose_name='TRAMO')),
            ],
            options={
                'verbose_name': 'Control Mensual de Equipo',
                'verbose_name_plural': 'Controles Mensuales de Equipos',
            },
        ),
    ]
