# Generated by Django 4.1.2 on 2024-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0008_alter_empleado_ingreso_alter_empleado_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='empedrado',
            field=models.BooleanField(blank=True, default=False, verbose_name='EMPEDRADO'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='km_final',
            field=models.IntegerField(blank=True, verbose_name='KM FINAL'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='km_inicial',
            field=models.IntegerField(blank=True, verbose_name='KM INICIAL'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='pavimento',
            field=models.BooleanField(blank=True, default=False, verbose_name='PAV.'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ripio',
            field=models.BooleanField(blank=True, default=False, verbose_name='RIPIO'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='seccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='SECCION'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tierra',
            field=models.BooleanField(blank=True, default=False, verbose_name='TIERRA'),
        ),
    ]
