# Generated by Django 4.1.2 on 2024-07-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0009_alter_ruta_empedrado_alter_ruta_km_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='INGRESO'),
        ),
    ]
