# Generated by Django 4.1.2 on 2024-07-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0010_alter_empleado_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='bomba_de_agua',
            field=models.BooleanField(blank=True, default=False, verbose_name='BOMBA DE AGUA'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='camion_aguatero',
            field=models.BooleanField(blank=True, default=False, verbose_name='CAMION AGUATERO'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='camioneta',
            field=models.BooleanField(blank=True, default=False, verbose_name='CAMIONETA'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='motoniveladora',
            field=models.BooleanField(blank=True, default=False, verbose_name='MOTONIVELADORA'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='produccion_diaria_max',
            field=models.FloatField(blank=True, verbose_name='PRODUCC DIARIA [MAX]'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='produccion_diaria_min',
            field=models.FloatField(blank=True, verbose_name='PRODUCC DIARIA [MIN]'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='produccion_diaria_prom',
            field=models.FloatField(blank=True, verbose_name='PRODUCC DIARIA [PROM]'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='produccion_hr_unid_prom',
            field=models.FloatField(blank=True, verbose_name='PRODUCC HR/UNID [PROM]'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='produccion_unid_hr_prom',
            field=models.FloatField(blank=True, verbose_name='PRODUCC UNID/HR [PROM]'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='unidad',
            field=models.CharField(blank=True, max_length=255, verbose_name='UNIDAD'),
        ),
        migrations.AlterField(
            model_name='entransito',
            name='numero_interno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_app.equipo', to_field='numero_interno', verbose_name='Número Interno'),
        ),
        migrations.AlterField(
            model_name='entransito',
            name='tipo_equipo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_interno',
            field=models.CharField(max_length=100, unique=True, verbose_name='N° INT.'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(max_length=255, verbose_name='TIPO EQUIPO'),
        ),
    ]
